# Site
name: 'daddyblondlegs'
description: 'World cyclist who dabbles as an expat. Bike part reviews, travelogues, and weird stories from life in China.'
logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: 'https://www.daddyblondlegs.com/'
disqus: 'demowebsite'
email: ''
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Daddy:
      name:           Daddy
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            Technophobe gracing tech companies in the Global 500, Fortune 500, a Kickstarter unicorn, and several little dinky places. Bike touring is my sanity factory.
      email:          
      twitter:        https://twitter.com/daddyblondlegs
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Daddy
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10
paginate_path: /page:num/

jekyll-archives:
  enabled: all
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

collections:
  category:
    output: true

    #clicky
    jekyll_clicky:              #Add this if you want to track with Clicky analytics
  site: daddyblondlegs.com
  id: 101457663         
