---
title:  "Cooking Setup for Bike Touring"
categories: [Gear, Bike Touring]
image: ""
tags: [Gear, Bike Touring, Tips]
---

<div class="container">

<div class="page-content">
   
  <div class="col-md-8 main-loop">

<h4 class="font-weight-bold spanborder" style="margin-bottom: 1rem;"><span>World Touring Cooking Setup</span></h4>
      <h5 class="pt-0 pb-0 mt-3 mb-2rem position-relative"><span style="font-weight: 200;">Welcome to the kitchen! Everything I need to cook just about anything fits into a shower tote bag. The key to a minimalist cooking setup is nesting and multipurposeness.</span></h5>
      <span style="display:inline-block; width: 10px;"></span>


<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="https://64.media.tumblr.com/02445ee2d120350ca909afb1f9da9637/07ea74d2f1f5b6f1-9e/s2048x3072/1c367bc99e7b9b15c7fc799d52dafcfdbbc64985.pnj" usemap="#image-map">

<map name="image-map">
    <area target="" alt="2L Aluminum Pot" title="2L Aluminum Pot" href="2L Aluminum Pot" coords="223,1669,223" shape="circle">
    <area target="" alt="Titanium camping cup" title="Titanium camping cup" href="Titanium camping cup" coords="308,1723,121" shape="circle">
    <area target="" alt="Silicon Collapseable/Resealable Bowl" title="Silicon Collapseable/Resealable Bowl" href="Silicon Collapseable/Resealable Bowl" coords="706,1666,227" shape="circle">
    <area target="" alt="Liquid Fuel Stove" title="Liquid Fuel Stove" href="Liquid Fuel Stove" coords="949,1488,1310,1851" shape="rect">
    <area target="" alt="Metal Spatula" title="Metal Spatula" href="Metal Spatula" coords="1314,1225,1238,1192,1206,1015,1196,874,1050,825,1077,651,1312,647,1314,805,1320,863" shape="poly">
    <area target="" alt="Multipurpose Scissors" title="Multipurpose Scissors" href="Multipurpose Scissors" coords="1122,895,1191,899,1183,1256,1234,1265,1236,1460,1056,1455,1088,1264,1125,1244" shape="poly">
    <area target="" alt="Fork and Spoon" title="Fork and Spoon" href="Fork and Spoon" coords="971,942,1102,1228" shape="rect">
    <area target="" alt="Coffee in Pill Bottle" title="Coffee in Pill Bottle" href="Coffee in Pill Bottle" coords="1027,143,1168,537" shape="rect">
    <area target="" alt="Bottle of Oil" title="Bottle of Oil" href="Bottle of Oil" coords="1280,563,1125,225" shape="rect">
    <area target="" alt="Spices" title="Spices" href="Spices" coords="60,81,363,343" shape="rect">
    <area target="" alt="Lighter" title="Lighter" href="Lighter" coords="93,409,306,491" shape="rect">
    <area target="" alt="Steel Wool" title="Steel Wool" href="Steel Wool" coords="120,623,89" shape="circle">
    <area target="" alt="Silicon Spatula" title="Silicon Spatula" href="Silicon Spatula" coords="236,506,372,758" shape="rect">
    <area target="" alt="Pot Gripper" title="Pot Gripper" href="Pot Gripper" coords="50,773,339,903" shape="rect">
    <area target="" alt="Foldable Windscreen" title="Foldable Windscreen" href="Foldable Windscreen" coords="46,940,330,1389" shape="rect">
    <area target="" alt="Tote Bag" title="Tote Bag" href="Tote Bag" coords="409,75,924,1375" shape="rect">
</map>


<br>
<h1>Kitchen Caddie:</h1>
<h2>LL Bean Toiletry Bag (Large)</h2>
<p>A toiletry bag I’ve had since the 9th grade was the absolute perfect bag for all of my cookware. It has several mesh pockets which keep from getting too nasty, a roomy interior, and a hook that hangs from my handlebars. Hanging it keeps bugs and mice out of my leftovers better than a tree can. The two-way zipper means that when one zipper goes out (which happened), you can use the other one (it also went out).</p>



<br>
<h1>Heat Source:</h1>
<h2>MSR Dragonfly Liquid Stove:</h2>
<p>This portable stove runs on gasoline you can get at any gas station, or diesel, jet fuel, and white gas. The versatility means you're likely to never be in a spot where you run out like you might be with gas canisters.</p>
<br>
<h2>Foldable Windscreen:</h2>
<p>The Dragonfly comes with a windscreen that is more like a heavy-duty foil, but I like the neatness of a foldable windscreen. Any brand will do, but get one that comes in a case - the sections are pretty thin and sharp. A windscreen isn't just for extreme conditions, I use mine every time I cook. Even the slightest bit of wind can put out the flame, and the windscreen directs heat up to the pot. What makes this better than foil windscreens is that when you run out of fuel, the it serves as a pot rest for wood fires.</p>
<br>
<h2>Lighter:</h2>
<p>Regular lighters work well, but I would try to find one with an electric spark so it can be used in the rain, and one that has a little bit of a neck to it because a windscreen makes it hard to get the flame close enough to the stove. Is a grill lighter overkill?</p>
<br>
<h1>Containers:</h1>
<h2>MSR Alpine Pot (2L):</h2>
<p>The set comes with two aluminum pots, but you only need one. Trust me, you won't be as gourmet as you think after a long day of riding, and you only have one burner. Usually it's boiling everything together, but if you want to make a topping (sauce, curry, gravy) for a base (rice, beans, pasta), pour it into one of your other containers while you cook the rest. The set also comes with a lid that doubles as a frying pan which you hold with the pot handler. The lid MSR Alpine line doesn't do a good job frying because it's too thin to heat up evenly over the concentrated flame of the stove.</p>
<br>
<h2>Sea to Summit X-Seal Bowl (XL):</h2>
<p>The collapseable bowl is a great space saver, but what make this indispensable is that lid is water-tight. Being able to cook for two meals means more time pedaling. What's great about this size, is that is sort of kind of seals the Alpine pot if you sandwich it between the pot and the lid and strap it down. It's not water-tight, but it's sauce-tight, mashed-potatoes, ant-tight. The Sea to Summit bowl also makes a great lid for your lid (so you can lid while you lid). Flip it over to form a dome, that traps in heat so the food in the lid cooks a little more uniformly.</p>
<br>
<h2>Camping Cup:</h2>
<p>This camping cup is the exact size of my stove, so it nests nicely. It's also the same diameter as the Jetboil French press plunger+screen.</p>
<br>
<h1>Utensils:</h1>
<h2>Multipurpose Scissors:</h2>
<p>Knives require cutting boards which requires flat surfaces which you'll never have. But scissors make light work of cutting. For big jobs like cutting squash, these detachable scissors have a knife on one side so you can cut the old-fashioned way using your lid as cutting board.</p>
<br>
<h2>Spatula (metal):</h2>
<p>I lost mine, and frankly never really needed it. A fork works just as good most times. I do miss it.</p>
<br>
<h1>Dry/Wet Ingredients:</h1>
<h2>Spices:</h2>
<p>My tote bag has a water-resistant pocket normally used for toiletries, but it makes a great place to store spice packets. The smallest salt shaker I could find is enough for the entire trip. Few places sell small bottles of oil, but the right size <b>bottle for oil</b> means you don't have to dump out as much when you refill it with a big container.</p>
<br>
<h2>Coffee in a Pill Bottle:</h2>
<p>An extra long pill bottle can hold about a week's worth of coffee. The advantage of storing it in the kitchen caddie is that it's easy to get to.</p>
<br>
<h1>Clean up:</h1>
<h2>Steel Wool:</h2>
<p>Notice I don't have a bar of soap or a sponge which require water. Steel wool scours pans and utensils, and can be cleaned with a good shake. Learning to tuck the steel wool's loose frizz neatly back on itself will mean you never need to get another one of these again.</p>
<br>
<h2>Spatula head (silicon):</h2>
<p>I found this on the side of the road in a box of kitchen items that fell off a truck. It's great at getting pots 95% clean so your steel wool can focus on the cooked one stuff. The edge of this thing is practically my dessert.</p>